#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  4 18:30:53 2022

@author: aegis
"""

import os
import pandas as pd
#from matplotlib.pyplot import pyplot as plt

PATH = r'/home/aegis/Dokumente/Masterarbeit/Data/Converted_files/'
files_daily = sorted(os.listdir(PATH + 'Daily/'))
files_weekly = sorted(os.listdir(PATH + 'Weekly/'))


# Read daily and weekly lvl data
print(files_daily[0])                                                   # Considering first file "kart"
df_daily_kart = pd.read_csv(PATH + 'Daily/' + files_daily[0], 
                            delimiter=';', decimal=',', header=0)

print(files_weekly[0])                                                  # Considering first file "kart"
df_weekly_kart = pd.read_csv(PATH + 'Weekly/' + files_weekly[0],
                             delimiter=';', decimal=',', header=0)

